---
- name: Check DigitalOcean Nodes
  hosts: localhost
  gather_facts: no
  vars:
    cloudconfig: "{{ lookup('file', 'files/coreos_cloudconfig.yml') }}"
  tasks:
    - name: Ensure SSH Keys Exist
      digital_ocean: >
        state=present
        command=ssh
        name={{ item.name }}
        ssh_pub_key="{{ lookup('file', '{{ item.file }}') }}"
      register: keys
      with_items:
        - { name: 'lcanal@BigPun'   , file: 'files/bigpun.pub', register_name: 'bigpun' }
        - { name: 'lcanal@donatello', file: 'files/donatello.pub', register_name: 'donatello' }

    - name: Ensure coreos-nodes are active
      digital_ocean: >
        state=present
        command=droplet
        name={{ item }}
        size_id=512mb
        region_id=sfo1
        image_id=coreos-beta
        unique_name=yes
        private_networking=yes
        ssh_key_ids="{{ keys.results[0].ssh_key.id }},{{ keys.results[1].ssh_key.id }}"
        user_data="{{ cloudconfig }}"
      with_items:
        - coreos-node1
        - coreos-node2
      register: droplets

    #- debug: var=droplets

   # - name: Ensure Node DNS names are active
   #    digital_ocean_domain: >
   #      state=present
   #      name={{ item.droplet.name }}.my.domain
   #      ip={{ item.droplet.ip_address }}
   #    with_items: droplets.results
