---
- include: do-deploy.yml

- name: Check DigitalOcean Nodes
  hosts: localhost
  connection: local
  gather_facts: no
  tasks:
    - name: Remove CoreOS nodes
      digital_ocean: >
        command=droplet
        id={{ item.droplet.id }}
        state=deleted
        size_id=512mb
        region_id=sfo1
        image_id=coreos-beta
      with_items:
        - "{{ droplets.results }}"
