---
- name: Ensure active hosts are bootstrapped
  hosts: status_active
  gather_facts: False
  vars_files:
    - vars/coreosbootstrap_vars.yml
  roles:
    - defunctzombie.coreos-bootstrap
    - wcl-bootstrap


- name: Ensure NGINX is installed
  hosts: status_active
  tasks:
    - name: NGINX
      docker:
        name: nginx
        image: nginx
        state: reloaded
        pull: missing
        ports:
          - "80:80"
