---
# Incorporate do-deploy into main site

- include: do-deploy.yml

- name: Ensure active hosts are bootstrapped
  hosts: status_active
  gather_facts: False
  vars_files:
    - vars/coreosbootstrap_vars.yml
  roles:
    - defunctzombie.coreos-bootstrap


