---
- name: Gather VM Facts
  vsphere_guest:
    guest: "{{ item }}"
    vcenter_hostname: "{{ esxihost }}"
    username: "{{ esxiuser }}"
    password: "{{ esxipass }}"
    vmware_guest_facts: yes
  with_items:
        - "{{ wcl_group }}"
  register: vmguest_facts
  delegate_to: localhost

- name: Cobbler dhcpd add
  template:
    src: dhcp.template.j2
    dest: /etc/cobbler/dhcp.template
  notify:
    - Cobbler Sync
    - SSH Wait
