---
- name: Provision Docker Nodes
  hosts: dockernodes
  connection: local
  gather_facts: false
  roles:
    - esxi-guest

- name: Cobbler dhcp entries
  hosts: dhcpd
  remote_user: root
  roles:
    - { role: cobbler-managed, wcl_group: "{{ groups['dockernodes'] }}" }

- name: Join IPA Realm
  hosts: dockernodes
  remote_user: root
  gather_facts: false
  tasks:
    - name: Install IPA client
      yum: name=ipa-client state=latest
      delegate_to: "{{ hostvars[inventory_hostname]['wcl_ip'] }}"
    - include: ipa-join-task.yml

- name: Turn into Docker Host 
  hosts: dockernodes
  remote_user: root
  roles:
    - docker-host

- name: Get Node Ready for Rancher
  hosts: dockernodes
  remote_user: root
  roles:
    - rancher-node
